module.exports.descriptors = [
    'OYO',
    'Madhuram',
    'Shreeji',
    'Saaya',
    'Shubash',
    'Abbad',
    'Shalini',
    'TownHouse',
    'BhootBangla',
    'Agrawal',
    'Somya',
    'Ganga',
    'Sairam',
    'Sundaram',
    'Apna',
    'Shuchin',
    'Hamza',
    'Shree Balaji'
]

module.exports.places = [
    'Flats Hotel',
    'Village Hotel',
    'Canyon Hotel',
    'Pond Hotel',
    'Group Hotel',
    'Horse Hotel',
    'Ghost Town Hotel',
    'Hotel',
    'Dispersed Hotel',
    'Backcountry Hotel',
    'River Hotel',
    'Creek Hotel',
    'Creekside Hotel',
    'Bay Hotel',
    'Spring Hotel',
    'Bayshore Hotel',
    'Sands Hotel',
    'Mule Hotel',
    'Hunting Hotel',
    'Cliffs Hotel',
    'Hollow Hotel'
]